### ISSUE TITLE
Create PR Template

### ISSUE THREAD

**Issue by franalgaba** [franalgaba/onnx-cairo#15]

**Comment by 1bhavyasingh1** [comment]
I would like to work on this

**Comment by franalgaba** [comment]
Hi @1bhavyasingh1 ! Of course, feel free to send here your proposal for PR template :)

**Comment by 1bhavyasingh1** [comment]
@franalgaba I have created a PR, please review it

**Comment by raphaelDkhn** [comment]
https://github.com/franalgaba/onnx-cairo/pull/31
